using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using AQASkeletronPlus.GUI;
using Config.Net;

namespace AQASkeletronPlus
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            //Set up the configuration file.
            Settings.Get = new ConfigurationBuilder<ISettings>().UseIniFile("settings.ini").Build();

            //If a settings file doesn't exist, try to make one.
            if (!File.Exists("settings.ini"))
            {
                try
                {
                    File.WriteAllText("settings.ini", "; This is an autogenerated settings file for AQA SKPE. Edit settings below.");
                }
                catch { }
            }

            //Run the main form.
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new StartupConfig());
        }
    }
}
